### ISSUE TITLE
Peer dependencies

### ISSUE THREAD

**Issue by jlarmstrongiv** [radarsu/ts-import#11]
I wonder if `tsc` and `typescript` should be included as `peerDependencies` in the `package.json`.  

See https://github.com/radarsu/ts-import/blob/master/src/index.ts#L177

If no, feel free to close.

**Comment by radarsu** [comment]
Due to `npx -p` flag latest typescript package will be pulled directly from npm registry, so currently there is no need for typescript peerDependency.

I should add an option though to allow configuring it. Some people may want to use their local version of typescript (that will also improve performance of compilation), some may want to use different version of typescript for the compilation process than they use.

**Comment by jlarmstrongiv** [comment]
> Some people may want to use their local version of typescript

Exactly 👍

**Comment by radarsu** [comment]
By default, when `npx -p typescript tsc` is executed, it runs local version if it exists.
